// frontend/src/app/login/page.tsx
'use client'

import Button from '@/components/atoms/button/button'
import { AppRouterInstance } from 'next/dist/shared/lib/app-router-context.shared-runtime'
import { useRouter } from 'next/navigation'
import { FormEvent } from 'react'
import { useAuth } from '@/context/AuthContext'

const Home = () => {
  const router: AppRouterInstance = useRouter()
  const { connectWithGoogle } = useAuth()

  const handlerSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    router.push('/dashboard')
  }

  return (
    <div className="c-login">
      <div>
        {/* <img src="/images/" alt="logo" /> */}
        <h4>Bienvenue !</h4>
        <p>Connectez-vous pour accéder à votre compte.</p>

        <form onSubmit={handlerSubmit}>
          <div className="c-input">
            <span className="c-input__subtitle">Email address</span>
            <input
              className="c-input__subtitle__input"
              type="email"
              placeholder="example@example.com"
              name="email"
              required
            />
          </div>

          <Button label="Se connecter" type="submit" size="large" />

          <hr />

          <Button
            label="Se connecter avec google"
            type="button"
            size="large"
            icon={<img src="/images/icons/google.svg" alt="" width={20} />}
            onClick={connectWithGoogle}
          />
        </form>
      </div>
    </div>
  )
}

export default Home

// frontend/src/routes/login/+page.svelte
<script>
    import Button from '$lib/components/atoms/Button.svelte';

    let email = '';

    const handlerSubmit = (event) => {
        event.preventDefault();
        // handle form submission
    };

    const connectWithGoogle = () => {
        // handle Google connection
    };
</script>

<div class="c-login">
    <div>
        <h4 class="text-black">Bienvenue !</h4>
        <p class="text-black">Connectez-vous pour accéder à votre compte.</p>

        <form on:submit={handlerSubmit}>
            <div class="c-input">
                <span class="c-input__subtitle">Email address</span>
                <input
                        class="c-input__subtitle__input"
                        type="email"
                        placeholder="example@example.com"
                        bind:value={email}
                        required
                />
            </div>

            <Button label="Se connecter" type="submit" size="large"/>

            <hr/>

            <Button
                    label="Se connecter avec google"
                    type="button"
                    size="large"
                    on:click={connectWithGoogle}
            />
        </form>
    </div>
</div>
