// frontend/src/lib/components/organisms/TopBar.svelte
<script lang="ts">
	import ThemeSwitcher from '$lib/components/atoms/ThemeSwitcher.svelte';
	import { Button } from '$lib/components/ui/button/index.js';

	import ButtonUi from '$lib/components/atoms/ButtonUi.svelte';

	import { FilePenLine } from 'lucide-svelte';

	import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';
	import CommandK from '$lib/components/atoms/CommandK.svelte';

</script>

<nav class="c-topbar">
	<div class="c-topbar__logo flex justify-between items-center gap-6">
		<h2 class="text-black text-xl">Hi Francis</h2>
	</div>

	<div class="c-topbar__container">
		<div class="c-topbar__container__left">
			<a href="/dashboard/invoices/add">
				<ButtonUi label="Create invoice">
					<FilePenLine class="w-5 h-5" />
				</ButtonUi>
			</a>
		</div>
	</div>

	<div class="c-topbar__container__right">
		<div class="c-topbar__container__right__item">
			<div class="c-profile-avatar">
				<div class="flex justify-center items-center text-black gap-6">
					<CommandK />

					<ThemeSwitcher />

					<DropdownMenu.Root>
						<DropdownMenu.Trigger asChild let:builder>
							<Button builders={[builder]} variant="outlet" class="flex items-center gap-2 bg-transparent">
								<img src="https://avatars.githubusercontent.com/u/1402241?v=4" class="w-8 h-8 rounded-full"
										 alt="avatar" />
							</Button>
						</DropdownMenu.Trigger>
						<DropdownMenu.Content class="w-56">
							<DropdownMenu.Label>Profil</DropdownMenu.Label>
							<DropdownMenu.Separator />
							<DropdownMenu.Label>
								<a href="/dashboard/account">
									Compte
								</a>
							</DropdownMenu.Label>
							<DropdownMenu.Separator />
							<DropdownMenu.Item>Déconnexion</DropdownMenu.Item>
						</DropdownMenu.Content>
					</DropdownMenu.Root>
				</div>
			</div>
		</div>
	</div>
</nav>

// frontend/src/components/organisms/topbar/topBar.tsx
'use client'

import {
  LogOut,
  User,
  Cloud,
  CreditCard,
  LifeBuoy,
  Mail,
  Settings,
  UserPlus,
  Users,
  FilePenLine,
  Building2,
} from 'lucide-react'

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuSeparator,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import CommandK from '@/components/atoms/command/CommandK'
import ButtonUI from '@/components/atoms/button/button'
import { Button } from '@/components/ui/button'
import { useAuth } from '@/context/AuthContext'
import Link from 'next/link'

const TopBar = () => {
  const { logout, user } = useAuth()

  return (
    <nav className="c-topbar">
      <div className="c-topbar__logo">
        <h2 className="text-black text-xl">
          Hi {(user && user.full_name) || (user && user.email)}
        </h2>
      </div>

      <div className="c-topbar__container">
        <div className="c-topbar__container__left">
          <ButtonUI
            label="Create invoice"
            icon={<FilePenLine className="w-5 h-5" />}
          />
        </div>
      </div>

      <div className="c-topbar__container">
        <div className="c-topbar__container__right">
          <div className="c-topbar__container__right__item">
            <div className="c-profile-avatar">
              <div className="flex justify-center items-center text-black gap-6">
                <CommandK />

                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline">
                      <img
                        src="https://avatars.githubusercontent.com/u/1402241?v=4"
                        className="w-8 h-8 rounded-full"
                        alt="avatar"
                      />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent className="w-56">
                    <DropdownMenuLabel>My Account</DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuGroup>
                      <Link href="/dashboard/account">
                        <DropdownMenuItem>
                          <User className="mr-2 h-4 w-4" />
                          <span>Profile</span>
                        </DropdownMenuItem>
                      </Link>
                      <DropdownMenuItem>
                        <CreditCard className="mr-2 h-4 w-4" />
                        <span>Billing</span>
                      </DropdownMenuItem>
                      <DropdownMenuItem>
                        <Settings className="mr-2 h-4 w-4" />
                        <span>Settings</span>
                      </DropdownMenuItem>
                    </DropdownMenuGroup>
                    <DropdownMenuSeparator />
                    <DropdownMenuGroup>
                      <DropdownMenuItem disabled>
                        <Users className="mr-2 h-4 w-4" />
                        <span>Team</span>
                      </DropdownMenuItem>
                      <Link href="/dashboard/compagny">
                        <DropdownMenuItem>
                          <Building2 className="mr-2 h-4 w-4" />
                          <span>Mon entreprise</span>
                        </DropdownMenuItem>
                      </Link>
                      <DropdownMenuSub>
                        <DropdownMenuSubTrigger>
                          <UserPlus className="mr-2 h-4 w-4" />
                          <span>Invite users</span>
                        </DropdownMenuSubTrigger>
                        <DropdownMenuPortal>
                          <DropdownMenuSubContent>
                            <DropdownMenuItem disabled>
                              <Mail className="mr-2 h-4 w-4" />
                              <span>Email</span>
                            </DropdownMenuItem>
                          </DropdownMenuSubContent>
                        </DropdownMenuPortal>
                      </DropdownMenuSub>
                    </DropdownMenuGroup>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem disabled>
                      <LifeBuoy className="mr-2 h-4 w-4" />
                      <span>Support</span>
                    </DropdownMenuItem>
                    <DropdownMenuItem disabled>
                      <Cloud className="mr-2 h-4 w-4" />
                      <span>API</span>
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem onClick={() => logout()}>
                      <LogOut className="mr-2 h-4 w-4" />
                      <span>Log out</span>
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
  )
}

export default TopBar
