// frontend/src/components/organisms/TopBar.svelte
<script>
	import ThemeSwitcher from '../atoms/ThemeSwitcher.svelte';
	import Button from '../atoms/Button.svelte';

	import { FilePenLine } from 'lucide-svelte';

</script>

<nav class="c-topbar">
	<div class="c-topbar__logo">
		<h2 class="text-black text-xl">Hi Francis</h2>
	</div>

	<div class="c-topbar__container">
		<div class="c-topbar__container__left">
			<Button label="Create invoice">
				<FilePenLine class="w-5 h-5" />
			</Button>
		</div>
	</div>
	<div class="c-topbar__container__right">
		<div class="c-topbar__container__right__item">
			<div class="c-profile-avatar">
				<div class="flex justify-center items-center text-black gap-2">
					<ThemeSwitcher />
					<p>Déconnexion</p>
				</div>
			</div>
		</div>
	</div>
</nav>

// frontend/src/components/organisms/topbar/topBar.tsx
'use client'

import { usePathname } from 'next/navigation'
import {
  LogOut,
  User,
  Cloud,
  CreditCard,
  Github,
  Keyboard,
  LifeBuoy,
  Mail,
  MessageSquare,
  Plus,
  PlusCircle,
  Settings,
  UserPlus,
  Users,
  FilePenLine,
} from 'lucide-react'

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import CommandK from '@/components/atoms/command/CommandK'
import ButtonUI from '@/components/atoms/button/button'
import { Button } from '@/components/ui/button'

const TopBar = () => (
  <nav className="c-topbar">
    <div className="c-topbar__logo">
      <h2 className="text-black text-xl">Hi Francis</h2>
    </div>

    <div className="c-topbar__container">
      <div className="c-topbar__container__left">
        <ButtonUI
          label="Create invoice"
          icon={<FilePenLine className="w-5 h-5" />}
        />
      </div>
    </div>

    <div className="c-topbar__container">
      <div className="c-topbar__container__right">
        <div className="c-topbar__container__right__item">
          <div className="c-profile-avatar">
            <div className="flex justify-center items-center text-black gap-6">
              <CommandK />

              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline">
                    <img
                      src="https://avatars.githubusercontent.com/u/1402241?v=4"
                      className="w-8 h-8 rounded-full"
                      alt="avatar"
                    />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="w-56">
                  <DropdownMenuLabel>My Account</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuGroup>
                    <DropdownMenuItem>
                      <User className="mr-2 h-4 w-4" />
                      <span>Profile</span>
                      <DropdownMenuShortcut>⇧⌘P</DropdownMenuShortcut>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <CreditCard className="mr-2 h-4 w-4" />
                      <span>Billing</span>
                      <DropdownMenuShortcut>⌘B</DropdownMenuShortcut>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Settings className="mr-2 h-4 w-4" />
                      <span>Settings</span>
                      <DropdownMenuShortcut>⌘S</DropdownMenuShortcut>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Keyboard className="mr-2 h-4 w-4" />
                      <span>Keyboard shortcuts</span>
                      <DropdownMenuShortcut>⌘K</DropdownMenuShortcut>
                    </DropdownMenuItem>
                  </DropdownMenuGroup>
                  <DropdownMenuSeparator />
                  <DropdownMenuGroup>
                    <DropdownMenuItem>
                      <Users className="mr-2 h-4 w-4" />
                      <span>Team</span>
                    </DropdownMenuItem>
                    <DropdownMenuSub>
                      <DropdownMenuSubTrigger>
                        <UserPlus className="mr-2 h-4 w-4" />
                        <span>Invite users</span>
                      </DropdownMenuSubTrigger>
                      <DropdownMenuPortal>
                        <DropdownMenuSubContent>
                          <DropdownMenuItem>
                            <Mail className="mr-2 h-4 w-4" />
                            <span>Email</span>
                          </DropdownMenuItem>
                          <DropdownMenuItem>
                            <MessageSquare className="mr-2 h-4 w-4" />
                            <span>Message</span>
                          </DropdownMenuItem>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem>
                            <PlusCircle className="mr-2 h-4 w-4" />
                            <span>More...</span>
                          </DropdownMenuItem>
                        </DropdownMenuSubContent>
                      </DropdownMenuPortal>
                    </DropdownMenuSub>
                    <DropdownMenuItem>
                      <Plus className="mr-2 h-4 w-4" />
                      <span>New Team</span>
                      <DropdownMenuShortcut>⌘+T</DropdownMenuShortcut>
                    </DropdownMenuItem>
                  </DropdownMenuGroup>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <Github className="mr-2 h-4 w-4" />
                    <span>GitHub</span>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <LifeBuoy className="mr-2 h-4 w-4" />
                    <span>Support</span>
                  </DropdownMenuItem>
                  <DropdownMenuItem disabled>
                    <Cloud className="mr-2 h-4 w-4" />
                    <span>API</span>
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <LogOut className="mr-2 h-4 w-4" />
                    <span>Log out</span>
                    <DropdownMenuShortcut>⇧⌘Q</DropdownMenuShortcut>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
)

export default TopBar
