// frontend/src/components/atoms/button/button.tsx
import React, { FunctionComponent } from 'react'
import ButtonProps from '@/types/ButtonProps'

const Button: FunctionComponent<ButtonProps> = ({
  primary = true,
  className,
  size = 'medium',
  label,
  backgroundColor,
  icon,
  onClick,
  type = 'button',
}) => {
  const mode = primary ? 'c-button--primary' : 'c-button--secondary'

  return (
    <button
      type={type}
      className={[
        'c-button',
        `c-button--${size}`,
        `c-button--${backgroundColor}`,
        `${className}`,

        mode,
      ].join(' ')}
      onClick={onClick}
    >
      <span>{icon}</span>
      <span>{label}</span>
    </button>
  )
}

export default Button

// frontend/src/components/atoms/Button.svelte
<script>
  export let primary = true;
  export let className = '';
  export let size = 'medium';
  export let label = '';
  export let backgroundColor = '';
  export let icon = null;
  export let onClick = null;
  export let type = 'button';

  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  function handleClick() {
    if (onClick) {
      onClick();
    }
    dispatch('click');
  }
</script>

<button
  type={type}
  class="c-button c-button--{size} c-button--{backgroundColor} {className} {primary ? 'c-button--primary' : 'c-button--secondary'}"
  on:click={handleClick}
>
  <span>{icon}</span>
  <span>{label}</span>
</button>
